
const S44_VERSION='S4.4 保守增强版';
const S44_S3={one:4/215,three:15/215,sixn:33/215,nine:49/215,fourz:75/215,sixz:104/215};
function s44Mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function s44Hr(a,w,base){const x=a.slice(-w);return x.length?s44Mean(x.map(Boolean).map(Number)):base}
function s44Choose(keys,hist,prev,base){if(!prev)prev=keys[0];const sc={};for(const k of keys)sc[k]=.65*s44Hr(hist[k],30,base)+.35*s44Hr(hist[k],60,base);let best=keys[0];for(const k of keys)if(sc[k]>sc[best])best=k;return sc[best]>=sc[prev]+.03?best:prev}
function s44Rescue5(base9,cov){const out=base9.slice(0,5);for(const n of rankedByScore(cov)){if(!out.includes(n))out.push(n);if(out.length===9)break}return out}
function s44ZSupport(final9,struct){const out={};for(const z of Object.keys(ZODIAC))out[z]=0;final9.forEach((n,i)=>out[numToZ[n]]+=1/Math.pow(i+1,.72));const z1=normalizeObj(out),z2=normalizeObj(struct),mix={};for(const z of Object.keys(out))mix[z]=.82*z1[z]+.18*z2[z];return mix}
function s44ZList(score,k){return Object.keys(score).sort((a,b)=>score[b]-score[a]).slice(0,k)}
function s44Miss(st,hit){if(hit)st.cur=0;else{st.cur++;st.max=Math.max(st.max,st.cur)}}
function s44ExtractS3Z(kind,count){
 const re=/(鼠|牛|虎|兔|龙|蛇|马|羊|猴|鸡|狗|猪)/g,keys=kind==='four'?["四肖（S1结构层）","四肖 (S1结构层)","四肖"]:["六肖（S1结构层）","六肖 (S1结构层)","六肖"];
 let best=null;
 for(const el of document.querySelectorAll('body *')){
  if(el.closest('#s44'))continue;const tx=(el.textContent||'').trim();if(!keys.some(k=>tx.includes(k)))continue;const zs=[...new Set(tx.match(re)||[])];if(zs.length>=count){if(!best||tx.length<best.tx.length)best={tx,zs:zs.slice(0,count)}}
 }
 return best?best.zs:null;
}
function s44SixEngine(hist,target){
 const bm=buildBaseMap(hist,target),actual={};hist.forEach(x=>actual[x.period]=x.special);const Hnine={A:[],B:[],C:[]},Hsix={A:[],B:[],C:[]};let prevNine='A',prevSix='A',current=null;const st={hit:0,cur:0,max:0};const last=Math.min(target-1,Math.max(...hist.map(x=>x.period)));
 for(let t=31;t<=target;t++){
  const base9=bm.base[t];if(!base9)continue;const cov=coverageScores(hist,t),nA=base9.slice(),nB=rescueNine(base9,cov),nC=s44Rescue5(base9,cov);prevNine=s44Choose(['A','B','C'],Hnine,prevNine,9/49);const nine={A:nA,B:nB,C:nC}[prevNine];
  const zBase4=zodiacFeatureScores(hist,t,nine,'base4'),zSix=zodiacFeatureScores(hist,t,nine,'six'),zSup4=s44ZSupport(nine,zBase4),zSup6=s44ZSupport(nine,zSix);
  const zCand={A:s44ZList(zSup6,6),B:s44ZList(zSix,6),C:(()=>{const a=s44ZList(zSup4,4);for(const z of s44ZList(zSix,12)){if(!a.includes(z))a.push(z);if(a.length===6)break}return a})()};
  prevSix=s44Choose(['A','B','C'],Hsix,prevSix,6/12);const six=zCand[prevSix];if(t===target)current={six,pick:prevSix,ninePick:prevNine};
  if(t<=last&&actual[t]!=null){const sp=actual[t],az=numToZ[sp];for(const c of ['A','B','C']){Hnine[c].push(({A:nA,B:nB,C:nC}[c]).includes(sp));Hsix[c].push(zCand[c].includes(az))}const hit=six.includes(az);if(hit)st.hit++;s44Miss(st,hit)}
 }
 return {current,stats:{n:last-30,st}};
}
function s44NumberStats(hist,target){const bm=buildBaseMap(hist,target),actual={};hist.forEach(x=>actual[x.period]=x.special),last=Math.min(target-1,Math.max(...hist.map(x=>x.period)));const S={one:{hit:0,cur:0,max:0},three:{hit:0,cur:0,max:0},sixn:{hit:0,cur:0,max:0},nine:{hit:0,cur:0,max:0}};for(let t=31;t<=last;t++){const r=bm.base[t];if(!r||actual[t]==null)continue;const sp=actual[t],h={one:r.slice(0,1).includes(sp),three:r.slice(0,3).includes(sp),sixn:r.slice(0,6).includes(sp),nine:r.includes(sp)};for(const k in h){if(h[k])S[k].hit++;s44Miss(S[k],h[k])}}return {bm,S,n:last-30}}
function s44Css(){return `<style id="s44style">#s44{max-width:820px;margin:14px auto 22px;padding:14px;color:#eef5ff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#s44 *{box-sizing:border-box}#s44 .hero{background:#111c31;border:1px solid #365173;border-radius:18px;padding:16px;box-shadow:0 10px 30px #0005}#s44 h1{margin:0 0 4px;font-size:23px}#s44 .sub{font-size:13px;color:#9fb1ca}#s44 .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}@media(max-width:560px){#s44 .grid{grid-template-columns:1fr}}#s44 .card{background:#0e182b;border:1px solid #2b405f;border-radius:13px;padding:12px}#s44 .lab{font-size:13px;color:#9fb1ca;margin-bottom:7px}#s44 .vals{font-size:20px;font-weight:800;line-height:1.5}#s44 .meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}#s44 .pill{font-size:12px;padding:5px 8px;border-radius:999px;background:#172640;border:1px solid #31486b}#s44 .good{color:#9fe3ad}.warn{color:#ffd98e}#s44 button{margin-top:12px;border:0;border-radius:10px;padding:10px 13px;font-weight:800;background:#e0ebff;color:#14223a}#s44 table{width:100%;border-collapse:collapse;margin-top:10px;font-size:13px}#s44 th,#s44 td{padding:8px 5px;border-bottom:1px solid #263a59;text-align:center}#s44 th:first-child,#s44 td:first-child{text-align:left}#s44 .note{font-size:12px;color:#91a3bc;line-height:1.55;margin-top:10px}</style>`}
function s44Render(){
 const hist=getHistory();if(!hist.length)return;const latest=Math.max(...hist.map(x=>x.period)),target=latest+1,NS=s44NumberStats(hist,target),base9=NS.bm.base[target];if(!base9)return;const ZE=s44SixEngine(hist,target),s3four=s44ExtractS3Z('four',4),s3six=s44ExtractS3Z('six',6),fallback4=s44ZList(s44ZSupport(base9,zodiacFeatureScores(hist,target,base9,'base4')),4),four=s3four||fallback4,newSix=ZE.current.six,newRate=ZE.stats.st.hit/ZE.stats.n,useNew=newRate>=S44_S3.sixz,six=useNew?newSix:(s3six||newSix);
 let root=document.getElementById('s44');if(!root){document.head.insertAdjacentHTML('beforeend',s44Css());root=document.createElement('section');root.id='s44';document.body.insertBefore(root,document.body.firstChild)}document.title='盘口 S4.4';
 const rows=[['⭐ 1码','one',S44_S3.one],['🎯 3码','three',S44_S3.three],['🔥 6码','sixn',S44_S3.sixn],['🟢 9码','nine',S44_S3.nine]];
 root.innerHTML=`<div class="hero"><h1>🛡️ ${S44_VERSION}</h1><div class="sub">历史1–${latest}期 · 当前预测${target}期 · S3作为硬底线，只保留网页严格回测真正跑赢的增强模块</div><div class="grid"><div class="card"><div class="lab">⭐ 1码 · S3底线</div><div class="vals">${base9.slice(0,1).map(fmt).join(' ')}</div></div><div class="card"><div class="lab">🎯 3码 · S3底线</div><div class="vals">${base9.slice(0,3).map(fmt).join(' ')}</div></div><div class="card"><div class="lab">🔥 6码 · S3底线</div><div class="vals">${base9.slice(0,6).map(fmt).join(' ')}</div></div><div class="card"><div class="lab">🟢 9码 · S3底线</div><div class="vals">${base9.map(fmt).join(' ')}</div></div><div class="card"><div class="lab">🐲 四肖 · 原S3结构层</div><div class="vals">${four.join('、')}</div></div><div class="card"><div class="lab">🐲 六肖 · ${useNew?'增强层':'已自动回退S3'}</div><div class="vals">${six.join('、')}</div></div></div><div class="meta"><span class="pill good">1/3/6/9码：锁定S3</span><span class="pill good">四肖：锁定S3</span><span class="pill ${useNew?'good':'warn'}">六肖：${useNew?'增强启用':'自动回退'}</span><span class="pill">六肖候选:${ZE.current.pick}</span></div><button id="s44bt">重新严格核验</button><div id="s44stats"><table><thead><tr><th>项目</th><th>S4.4/当前命中</th><th>命中率</th><th>最长连空</th><th>S3底线</th></tr></thead><tbody>${rows.map(([lab,k,br])=>{const v=NS.S[k];return `<tr><td>${lab}</td><td>${v.hit}/${NS.n}</td><td class="good">${(v.hit/NS.n*100).toFixed(2)}%</td><td>${v.max}期</td><td>${(br*100).toFixed(2)}%</td></tr>`}).join('')}<tr><td>🐲 四肖</td><td>75/215 基线</td><td class="good">34.88%</td><td>—</td><td>34.88%</td></tr><tr><td>🐲 六肖</td><td>${ZE.stats.st.hit}/${ZE.stats.n}</td><td class="${useNew?'good':'warn'}">${(newRate*100).toFixed(2)}%</td><td>${ZE.stats.st.max}期</td><td>48.37%</td></tr></tbody></table></div><div class="note">保护规则：号码层与四肖不再参与自动择优，直接采用已验证的S3；六肖保留自适应覆盖候选，但只有完整逐期回测命中率不低于S3的48.37%时才启用，否则自动显示原S3六肖。以后新期开奖只记盲测，不反改过去规则。四肖当前值优先读取下方原S3结构层。</div></div>`;document.getElementById('s44bt').onclick=s44Render;
}
setTimeout(s44Render,900);let s44sig='';setInterval(()=>{try{const h=getHistory(),x=h.length?`${h.length}:${h[h.length-1].period}:${h[h.length-1].special}`:'';if(x!==s44sig){s44sig=x;s44Render()}}catch(e){console.log(e)}},2200);
