
const S44S_VERSION='S4.4 保守增强版';
(function(){
  const st=document.createElement('style');
  st.textContent='#s43{display:none!important}#s44s{max-width:820px;margin:14px auto 22px;padding:14px;color:#eef5ff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#s44s *{box-sizing:border-box}#s44s .hero{background:#111c31;border:1px solid #365173;border-radius:18px;padding:16px;box-shadow:0 10px 30px #0005}#s44s h1{margin:0 0 4px;font-size:23px}#s44s .sub{font-size:13px;color:#9fb1ca}#s44s .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}@media(max-width:560px){#s44s .grid{grid-template-columns:1fr}}#s44s .card{background:#0e182b;border:1px solid #2b405f;border-radius:13px;padding:12px}#s44s .lab{font-size:13px;color:#9fb1ca;margin-bottom:7px}#s44s .vals{font-size:20px;font-weight:800;line-height:1.5}#s44s .meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}#s44s .pill{font-size:12px;padding:5px 8px;border-radius:999px;background:#172640;border:1px solid #31486b}#s44s .good{color:#9fe3ad}#s44s .warn{color:#ffd98e}#s44s table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px}#s44s th,#s44s td{padding:8px 5px;border-bottom:1px solid #263a59;text-align:center}#s44s th:first-child,#s44s td:first-child{text-align:left}#s44s .note{font-size:12px;color:#91a3bc;line-height:1.55;margin-top:10px}';
  document.head.appendChild(st);
})();
function s44sRender(){
 try{
  if(typeof draws==='undefined'||typeof predict!=='function'||typeof s43Compute!=='function')return;
  const hist=draws.slice().sort((a,b)=>a.period-b.period),latest=hist[hist.length-1].period,target=latest+1;
  const base=predict(hist,target),r43=s43Compute(hist,target,true),enh=r43.current&&r43.current.sixz?r43.current.sixz:base.sixZ;
  const n=r43.stats&&r43.stats.n?r43.stats.n:215,sixHit=r43.stats&&r43.stats.S?r43.stats.S.sixz.hit:0,sixMax=r43.stats&&r43.stats.S?r43.stats.S.sixz.max:0;
  const useNew=sixHit>=104,six=useNew?enh:base.sixZ;
  let root=document.getElementById('s44s');if(!root){root=document.createElement('section');root.id='s44s';document.body.insertBefore(root,document.body.firstChild)}
  const old=document.querySelector('body > .wrap h1, .wrap h1');if(old&&!old.dataset.s44renamed){old.textContent='S3 基础引擎（S4.4数据录入区）';old.dataset.s44renamed='1'}
  document.title='盘口 S4.4';
  const b=r43.stats&&r43.stats.B?r43.stats.B:{one:4,three:15,sixn:33,nine:49};
  root.innerHTML=`<div class="hero"><h1>🛡️ ${S44S_VERSION}</h1><div class="sub">历史1–${latest}期 · 当前预测${target}期 · 号码层与四肖锁定S3，六肖只在严格回测不低于S3时启用增强</div><div class="grid"><div class="card"><div class="lab">⭐ 1码 · S3底线</div><div class="vals">${fmt(base.rank[0])}</div></div><div class="card"><div class="lab">🎯 3码 · S3底线</div><div class="vals">${base.rank.slice(0,3).map(fmt).join(' ')}</div></div><div class="card"><div class="lab">🔥 6码 · S3底线</div><div class="vals">${base.rank.slice(0,6).map(fmt).join(' ')}</div></div><div class="card"><div class="lab">🟢 9码 · S3底线</div><div class="vals">${base.rank.slice(0,9).map(fmt).join(' ')}</div></div><div class="card"><div class="lab">🐲 四肖 · 原S3结构层</div><div class="vals">${base.fourZ.join('、')}</div></div><div class="card"><div class="lab">🐲 六肖 · ${useNew?'增强层':'自动回退S3'}</div><div class="vals">${six.join('、')}</div></div></div><div class="meta"><span class="pill good">1/3/6/9码：S3锁定</span><span class="pill good">四肖：S3锁定</span><span class="pill ${useNew?'good':'warn'}">六肖：${useNew?'增强启用':'回退S3'}</span></div><table><thead><tr><th>项目</th><th>严格回测</th><th>命中率</th><th>保护状态</th></tr></thead><tbody><tr><td>⭐ 1码</td><td>${b.one}/${n}</td><td>${(b.one/n*100).toFixed(2)}%</td><td class="good">S3底线</td></tr><tr><td>🎯 3码</td><td>${b.three}/${n}</td><td>${(b.three/n*100).toFixed(2)}%</td><td class="good">S3底线</td></tr><tr><td>🔥 6码</td><td>${b.sixn}/${n}</td><td>${(b.sixn/n*100).toFixed(2)}%</td><td class="good">S3底线</td></tr><tr><td>🟢 9码</td><td>${b.nine}/${n}</td><td>${(b.nine/n*100).toFixed(2)}%</td><td class="good">S3底线</td></tr><tr><td>🐲 四肖</td><td>75/${n}</td><td>${(75/n*100).toFixed(2)}%</td><td class="good">S3底线</td></tr><tr><td>🐲 六肖</td><td>${sixHit}/${n}</td><td>${(sixHit/n*100).toFixed(2)}%</td><td class="${useNew?'good':'warn'}">${useNew?'增强启用':'自动回退'}</td></tr></tbody></table><div class="note">这版不再让新算法覆盖已经更好的S3号码层。六肖沿用S4.3中实际可复现的增强候选；若其完整逐期回测低于S3六肖104/${n}，自动回退原S3六肖。以后新增开奖结果只做盲测，不反改过去规则。</div></div>`;
 }catch(e){console.error('S4.4 render error',e)}
}
setTimeout(s44sRender,1100);let s44ssig='';setInterval(()=>{try{if(typeof draws==='undefined'||!draws.length)return;const d=draws[draws.length-1],x=`${draws.length}:${d.period}:${d.special}`;if(x!==s44ssig){s44ssig=x;s44sRender()}}catch(e){console.error(e)}},2200);
